### ISSUE TITLE
Implement mintFor using DAI's permit function

### ISSUE THREAD

**Issue by hellwolf** [rtoken-project/rtoken-monorepo#36]
https://medium.com/@Degens/betting-without-eth-dais-new-permit-feature-5517293f3246

"This new feature allows the approval process to be done by a separate party, same as our bet on the Rams above" / A meta transaction for approve if you will.

ACs:

- Add `mintFor`/`mintForWithSelectedHat`/`mintForWithNewHat` to RDai, which uses DAI's permit function internally.
- Implement the new functions
- Test case
  - `bob` signs permit
  - `business` mintFor `bob` with `bob`'s signature
  - `bob` receives rDai without using ETH.

Bounty size: 100 rĐ

**Comment by hellwolf** [comment]
@pi0neerpat do you mind if we take this as a bounty for 100 rĐ ?

**Comment by pi0neerpat** [comment]
Sure go ahead. After research from rTrees, I concluded that this was actually not very valuable. This would require a relayer  (could use mosendo) for the approval, but the user still needs gas ETH for any rtoken function call like mint.

**Comment by hellwolf** [comment]
> Sure go ahead. After research from rTrees, I concluded that this was actually not very valuable. This would require a relayer (could use mosendo) for the approval, but the user still needs gas ETH for any rtoken function call like mint.
> 
> If you wanted to get real fancy, you take the user's dai, mint rDAI in another account, and send it to the user. But that's getting into more "product" territory and away from core rToken functionality

Interesting, some "mintFor" function?

**Comment by hellwolf** [comment]
> Sure go ahead. After research from rTrees, I concluded that this was actually not very valuable. This would require a relayer (could use mosendo) for the approval, but the user still needs gas ETH for any rtoken function call like mint.
> 
> If you wanted to get real fancy, you take the user's dai, mint rDAI in another account, and send it to the user. But that's getting into more "product" territory and away from core rToken functionality

Yes, you are right, the `mintFor`, `mintForWithSelectedhat` and `mintForWithNewHat` functions.

**Comment by pi0neerpat** [comment]
That would work

**Comment by pi0neerpat** [comment]
closed by #45
